# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &Ord1

        Name: Ord1

        ID: Ord1MSP

        MSPDir: ./crypto-config/ordererOrganizations/ord1.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Ord1MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('Ord1MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('Ord1MSP.admin')"

    - &Ord2

        Name: Ord2

        ID: Ord2MSP

        MSPDir: ./crypto-config/ordererOrganizations/ord2.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Ord2MSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('Ord2MSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('Ord2MSP.admin')"

    - &Org1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org1MSP

        # ID to load the MSP definition as
        ID: Org1MSP

        MSPDir: ./crypto-config/peerOrganizations/org1.example.com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org1MSP.peer')"

        # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org1.example.com
              Port: 7051

    - &Org2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org2MSP

        # ID to load the MSP definition as
        ID: Org2MSP

        MSPDir: ./crypto-config/peerOrganizations/org2.example.com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org2MSP.peer')"

        AnchorPeers:

            - Host: peer0.org2.example.com
              Port: 17051

Capabilities:

    Channel: &ChannelCapabilities

        V2_0: true

    Orderer: &OrdererCapabilities

        V2_0: true

    Application: &ApplicationCapabilities

        V2_0: true

################################################################################
#
#   SECTION: Application
#
################################################################################
Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

    OrdererType: etcdraft

    Addresses:
        - orderer1.ord1.example.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#
#   CHANNEL
#
################################################################################
Channel: &ChannelDefaults

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
################################################################################
Profiles:

    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
            Capabilities:
                <<: *ApplicationCapabilities

    SampleMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer1.ord1.example.com
                  Port: 7050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer1.ord1.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer1.ord1.example.com/tls/server.crt
                - Host: orderer2.ord1.example.com
                  Port: 8050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer2.ord1.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer2.ord1.example.com/tls/server.crt
                - Host: orderer3.ord1.example.com
                  Port: 9050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer3.ord1.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer3.ord1.example.com/tls/server.crt
                - Host: orderer4.ord1.example.com
                  Port: 10050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer4.ord1.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer4.ord1.example.com/tls/server.crt
                - Host: orderer5.ord1.example.com
                  Port: 11050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer5.ord1.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer5.ord1.example.com/tls/server.crt
                - Host: orderer6.ord1.example.com
                  Port: 12050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer6.ord1.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer6.ord1.example.com/tls/server.crt
                - Host: orderer7.ord1.example.com
                  Port: 13050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer7.ord1.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer7.ord1.example.com/tls/server.crt
                - Host: orderer8.ord1.example.com
                  Port: 14050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer8.ord1.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord1.example.com/orderers/orderer8.ord1.example.com/tls/server.crt
                - Host: orderer1.ord2.example.com
                  Port: 17050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer1.ord2.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer1.ord2.example.com/tls/server.crt
                - Host: orderer2.ord2.example.com
                  Port: 18050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer2.ord2.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer2.ord2.example.com/tls/server.crt
                - Host: orderer3.ord2.example.com
                  Port: 19050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer3.ord2.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer3.ord2.example.com/tls/server.crt
                - Host: orderer4.ord2.example.com
                  Port: 20050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer4.ord2.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer4.ord2.example.com/tls/server.crt
                - Host: orderer5.ord2.example.com
                  Port: 21050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer5.ord2.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer5.ord2.example.com/tls/server.crt
                - Host: orderer6.ord2.example.com
                  Port: 22050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer6.ord2.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer6.ord2.example.com/tls/server.crt
                - Host: orderer7.ord2.example.com
                  Port: 23050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer7.ord2.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer7.ord2.example.com/tls/server.crt
                - Host: orderer8.ord2.example.com
                  Port: 23050
                  ClientTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer8.ord2.example.com/tls/server.crt
                  ServerTLSCert: ./crypto-config/ordererOrganizations/ord2.example.com/orderers/orderer8.ord2.example.com/tls/server.crt
               
            Addresses:
                - orderer1.ord1.example.com:7050
                - orderer2.ord1.example.com:8050
                - orderer3.ord1.example.com:9050
                - orderer4.ord1.example.com:10050
                - orderer5.ord1.example.com:11050
                - orderer6.ord1.example.com:12050
                - orderer7.ord1.example.com:13050
                - orderer8.ord1.example.com:14050
                - orderer1.ord2.example.com:17050
                - orderer2.ord2.example.com:18050
                - orderer3.ord2.example.com:19050
                - orderer4.ord2.example.com:20050
                - orderer5.ord2.example.com:21050
                - orderer6.ord2.example.com:22050
                - orderer7.ord2.example.com:23050
                - orderer8.ord1.example.com:24050

            Organizations:
            - *Ord1
            - *Ord2
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *Ord1
            - <<: *Ord2
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Org1
                - *Org2